from_output = false
web = false
youtube_url = "https://www.youtube.com/watch?v=EFdGChPBN4k"
input_lang = "en"
output_lang = "en"
scribe_text = "scribeai1.txt"
scribe_voice = "scribeai.mp3"
scribe_backend = "faster-whisper"
scribe_model = "large-v3"
scribe_vad = false
magnitude_threshold = 0.01
whispercpp_bin = "C:\\Users\\other\\whisper.cpp\\build\\bin\\Release\\whisper-cli.exe"
whispercpp_model_dir = "./models"
whispercpp_threads = 4
no_auto_download = false
whispercpp_cli_detect_lang = false
whisper_ctranslate2_device = "auto"
whisper_ctranslate2_compute_type = "default"
slate_backend = "googletrans"
voice_backend = "gtts"
voice_model = "en_US-lessac-medium"
voice_match = false
window_seconds = 5.0
overlap_seconds = 0.0
mqtt_port = 1883
mqtt_topic = "translation"
web_host = "0.0.0.0"
web_port = 8443
web_ssl_self_signed = false
youtube_api_key = "AIzaSyAUGtf3IXrjjjgYpXr9E2F-Hj99vkbfo9E"
youtube_remote_components = "ejs:github"
list_output_devices = false
chat_log = "./chat"
batch_input_text = 0
verbose = false
timers = false
timers_all = false
lang_prefix = false
keep_temp = false
dedup = false
looptran = 0
no_norm = false
no_input_norm = false
