rtsp = ["rtsp://Smartthings:3xDZAjrVMrGPvdub@192.168.1.113:554//h265Preview_01_sub"]
from_output = false
web = false
input_lang = "auto"
output_lang = "en"
scribe_backend = "faster-whisper"
scribe_model = "small"
scribe_vad = true
magnitude_threshold = 0.001
whispercpp_bin = "C:\\Users\\other\\whisper.cpp\\build\\bin\\Release\\whisper-cli.exe"
whispercpp_model_dir = "./models"
whispercpp_threads = 4
no_auto_download = false
whispercpp_cli_detect_lang = false
whisper_ctranslate2_device = "auto"
whisper_ctranslate2_compute_type = "default"
slate_backend = "googletrans"
voice_backend = "gtts"
voice_model = "en_US-lessac-medium"
voice_match = false
window_seconds = 5.0
overlap_seconds = 0.0
mqtt_port = 1883
mqtt_topic = "translation"
web_host = "0.0.0.0"
web_port = 8443
web_ssl_self_signed = false
youtube_remote_components = "ejs:github"
list_output_devices = false
chat_log = "chat"
batch_input_text = 0
verbose = true
timers = false
timers_all = false
lang_prefix = false
keep_temp = false
dedup = false
looptran = 0
no_norm = false
no_input_norm = false
